//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcg_load
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Plantas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_Plantas()
        {
            this.Esc_Lineas = new HashSet<Esc_Lineas>();
            this.Esc_Horas = new HashSet<Esc_Horas>();
            this.Esc_OEE = new HashSet<Esc_OEE>();
            this.Esc_OEEDesglose = new HashSet<Esc_OEEDesglose>();
            this.Esc_Articulos = new HashSet<Esc_Articulos>();
            this.Esc_Maquina = new HashSet<Esc_Maquina>();
        }
    
        public string Planta { get; set; }
        public Nullable<int> org_id { get; set; }
        public string Nombre { get; set; }
        public string nombre_planta { get; set; }
        public string OI { get; set; }
        public string Site { get; set; }
        public string Site_largo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Lineas> Esc_Lineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Horas> Esc_Horas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_OEE> Esc_OEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_OEEDesglose> Esc_OEEDesglose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Articulos> Esc_Articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Maquina> Esc_Maquina { get; set; }
    }
}
