//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcg_load
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esc_Horas_staging
    {
        public string Planta { get; set; }
        public string Linea { get; set; }
        public System.DateTime Fecha { get; set; }
        public int id_escenario { get; set; }
        public string UserId { get; set; }
        public Nullable<double> Horas { get; set; }
        public Nullable<double> Horas_base { get; set; }
        public Nullable<bool> modificado { get; set; }
        public string UserId_modifico { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    }
}
