//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcg_load
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esc_Año
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esc_Año()
        {
            this.Esc_Parametros = new HashSet<Esc_Parametros>();
            this.Esc_Rechazo = new HashSet<Esc_Rechazo>();
            this.Esc_OEEDesglose = new HashSet<Esc_OEEDesglose>();
            this.Esc_OEECorazones = new HashSet<Esc_OEECorazones>();
            this.Esc_Velocidad = new HashSet<Esc_Velocidad>();
            this.Esc_Cavidades = new HashSet<Esc_Cavidades>();
        }
    
        public int Año { get; set; }
        public int Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Parametros> Esc_Parametros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Rechazo> Esc_Rechazo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_OEEDesglose> Esc_OEEDesglose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_OEECorazones> Esc_OEECorazones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Velocidad> Esc_Velocidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Cavidades> Esc_Cavidades { get; set; }
        public virtual Esc_Calendario Esc_Calendario { get; set; }
    }
}
