//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcg_load
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esc_Demanda_staging
    {
        public double id_articulo { get; set; }
        public System.DateTime fecha02 { get; set; }
        public int Fecha { get; set; }
        public int id_escenario { get; set; }
        public string UserId { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> Valor_base { get; set; }
        public Nullable<bool> eliminado { get; set; }
    }
}
