//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcg_load
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esc_Calendario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esc_Calendario()
        {
            this.Cat_Bitacora = new HashSet<Cat_Bitacora>();
            this.Esc_Año = new HashSet<Esc_Año>();
            this.Esc_Demanda = new HashSet<Esc_Demanda>();
            this.Esc_HorasCorazones = new HashSet<Esc_HorasCorazones>();
            this.Esc_Horas = new HashSet<Esc_Horas>();
            this.Esc_OEE = new HashSet<Esc_OEE>();
        }
    
        public int Fecha { get; set; }
        public System.DateTime fecha02 { get; set; }
        public byte dia { get; set; }
        public byte dia_semana { get; set; }
        public string dia_semana_desc { get; set; }
        public bool es_fin_semana { get; set; }
        public bool es_asueto { get; set; }
        public string asueto_desc { get; set; }
        public byte dia_mes { get; set; }
        public short dia_anio { get; set; }
        public byte semana_mes { get; set; }
        public byte semana_anio { get; set; }
        public byte semana_anio_iso { get; set; }
        public byte mes { get; set; }
        public string mes_desc { get; set; }
        public byte trimestre { get; set; }
        public string trimestre_desc { get; set; }
        public int anio { get; set; }
        public string mmyyyy { get; set; }
        public string mes_anio { get; set; }
        public System.DateTime primer_dia_mes { get; set; }
        public System.DateTime ultimo_dia_mes { get; set; }
        public System.DateTime primer_dia_trimestre { get; set; }
        public System.DateTime ultimo_dia_trimestre { get; set; }
        public System.DateTime primer_dia_anio { get; set; }
        public System.DateTime ultimo_dia_anio { get; set; }
        public System.DateTime primer_dia_siguiente_mes { get; set; }
        public System.DateTime primer_dia_siguiente_anio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Bitacora> Cat_Bitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Año> Esc_Año { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Demanda> Esc_Demanda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_HorasCorazones> Esc_HorasCorazones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Horas> Esc_Horas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_OEE> Esc_OEE { get; set; }
    }
}
