//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcg_load
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esc_Escenario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esc_Escenario()
        {
            this.Cat_Bitacora = new HashSet<Cat_Bitacora>();
            this.Esc_Articulos = new HashSet<Esc_Articulos>();
            this.Esc_Cavidades = new HashSet<Esc_Cavidades>();
            this.Esc_Demanda = new HashSet<Esc_Demanda>();
            this.Esc_Velocidad = new HashSet<Esc_Velocidad>();
            this.Esc_Rechazo = new HashSet<Esc_Rechazo>();
            this.Esc_Horas = new HashSet<Esc_Horas>();
            this.Esc_HorasCorazones = new HashSet<Esc_HorasCorazones>();
            this.Esc_OEE = new HashSet<Esc_OEE>();
            this.Esc_OEECorazones = new HashSet<Esc_OEECorazones>();
            this.Esc_OEEDesglose = new HashSet<Esc_OEEDesglose>();
        }
    
        public int id_escenario { get; set; }
        public int id_UpLoad { get; set; }
        public int id_tipo_escenario { get; set; }
        public string UserId { get; set; }
        public string comentario { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<bool> modificado { get; set; }
        public string UserId_modifico { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Bitacora> Cat_Bitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Articulos> Esc_Articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Cavidades> Esc_Cavidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Demanda> Esc_Demanda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Velocidad> Esc_Velocidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Rechazo> Esc_Rechazo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Horas> Esc_Horas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_HorasCorazones> Esc_HorasCorazones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_OEE> Esc_OEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_OEECorazones> Esc_OEECorazones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_OEEDesglose> Esc_OEEDesglose { get; set; }
        public virtual Esc_File_Upload Esc_File_Upload { get; set; }
        public virtual Esc_Tipo_Escenarios Esc_Tipo_Escenarios { get; set; }
    }
}
