//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcg_load
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esc_Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esc_Articulos()
        {
            this.Esc_Rechazo = new HashSet<Esc_Rechazo>();
            this.Esc_Cavidades = new HashSet<Esc_Cavidades>();
            this.Esc_Demanda = new HashSet<Esc_Demanda>();
            this.Esc_Velocidad = new HashSet<Esc_Velocidad>();
            this.Esc_Parametros = new HashSet<Esc_Parametros>();
        }
    
        public double id_articulo { get; set; }
        public int id_escenario { get; set; }
        public Nullable<double> Org__ID { get; set; }
        public string Escenario { get; set; }
        public string Probabilidad { get; set; }
        public string Línea_Moldeo { get; set; }
        public string Cliente { get; set; }
        public string Customer_Name { get; set; }
        public string Industria { get; set; }
        public string Tipo_Pieza { get; set; }
        public string Description { get; set; }
        public string No__Oracle { get; set; }
        public string Customer_PN { get; set; }
        public Nullable<double> Unit_Weight { get; set; }
        public string Mercado { get; set; }
        public string Tipo_de_Hierro { get; set; }
        public string Grado_de_Hierro { get; set; }
        public string OEM { get; set; }
        public string Plataforma { get; set; }
        public string Sistema { get; set; }
        public Nullable<double> Cavs____Soplo { get; set; }
        public Nullable<double> Soplos___Hora { get; set; }
        public Nullable<double> Cor___pza { get; set; }
        public string Maquina { get; set; }
        public Nullable<int> id_maquina { get; set; }
        public string Planta { get; set; }
        public string Planta01 { get; set; }
        public string Linea { get; set; }
        public Nullable<bool> modificado { get; set; }
        public string UserId_modifico { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual CAT_Plantas CAT_Plantas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Rechazo> Esc_Rechazo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Cavidades> Esc_Cavidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Demanda> Esc_Demanda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Velocidad> Esc_Velocidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Parametros> Esc_Parametros { get; set; }
        public virtual Esc_Escenario Esc_Escenario { get; set; }
        public virtual Esc_Lineas Esc_Lineas { get; set; }
        public virtual Esc_Maquina Esc_Maquina { get; set; }
    }
}
