//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcg_load
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esc_File_Upload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esc_File_Upload()
        {
            this.Esc_Escenario = new HashSet<Esc_Escenario>();
        }
    
        public int id_UpLoad { get; set; }
        public string UserId { get; set; }
        public string nombre { get; set; }
        public string comentario { get; set; }
        public string FileName { get; set; }
        public long ContentLength { get; set; }
        public string ContentType { get; set; }
        public string TempFileName { get; set; }
        public Nullable<System.DateTime> date_uplodad { get; set; }
        public string hashFile { get; set; }
        public Nullable<bool> eliminado { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esc_Escenario> Esc_Escenario { get; set; }
    }
}
