//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcg_load
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mcg_saturacionEntities : DbContext
    {
        public mcg_saturacionEntities()
            : base("name=mcg_saturacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Cat_Bitacora> Cat_Bitacora { get; set; }
        public virtual DbSet<CAT_Plantas> CAT_Plantas { get; set; }
        public virtual DbSet<Esc_Actualizacion> Esc_Actualizacion { get; set; }
        public virtual DbSet<Esc_Año> Esc_Año { get; set; }
        public virtual DbSet<Esc_Articulos> Esc_Articulos { get; set; }
        public virtual DbSet<Esc_Calendario> Esc_Calendario { get; set; }
        public virtual DbSet<Esc_Cavidades> Esc_Cavidades { get; set; }
        public virtual DbSet<Esc_Demanda> Esc_Demanda { get; set; }
        public virtual DbSet<Esc_Demanda_staging> Esc_Demanda_staging { get; set; }
        public virtual DbSet<Esc_Escenario> Esc_Escenario { get; set; }
        public virtual DbSet<Esc_File_Upload> Esc_File_Upload { get; set; }
        public virtual DbSet<Esc_Horas> Esc_Horas { get; set; }
        public virtual DbSet<Esc_Horas_staging> Esc_Horas_staging { get; set; }
        public virtual DbSet<Esc_HorasCorazones> Esc_HorasCorazones { get; set; }
        public virtual DbSet<Esc_HorasCorazones_staging> Esc_HorasCorazones_staging { get; set; }
        public virtual DbSet<Esc_Lineas> Esc_Lineas { get; set; }
        public virtual DbSet<Esc_Lineas_staging> Esc_Lineas_staging { get; set; }
        public virtual DbSet<Esc_Maquina> Esc_Maquina { get; set; }
        public virtual DbSet<Esc_OEE> Esc_OEE { get; set; }
        public virtual DbSet<Esc_OEE_staging> Esc_OEE_staging { get; set; }
        public virtual DbSet<Esc_OEECorazones> Esc_OEECorazones { get; set; }
        public virtual DbSet<Esc_OEEDesglose> Esc_OEEDesglose { get; set; }
        public virtual DbSet<Esc_Parametros> Esc_Parametros { get; set; }
        public virtual DbSet<Esc_Rechazo> Esc_Rechazo { get; set; }
        public virtual DbSet<Esc_Tipo_Escenarios> Esc_Tipo_Escenarios { get; set; }
        public virtual DbSet<Esc_Tipo_linea> Esc_Tipo_linea { get; set; }
        public virtual DbSet<Esc_Velocidad> Esc_Velocidad { get; set; }
        public virtual DbSet<vw_demanda> vw_demanda { get; set; }
        public virtual DbSet<vw_demanda01> vw_demanda01 { get; set; }
    }
}
