//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcg_load
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_demanda01
    {
        public int anio { get; set; }
        public double id_articulo { get; set; }
        public string Description { get; set; }
        public int id_escenario { get; set; }
        public Nullable<double> Enero { get; set; }
        public Nullable<double> Febrero { get; set; }
        public Nullable<double> Marzo { get; set; }
        public Nullable<double> Abril { get; set; }
        public Nullable<double> Mayo { get; set; }
        public Nullable<double> Junio { get; set; }
        public Nullable<double> Julio { get; set; }
        public Nullable<double> Agosto { get; set; }
        public Nullable<double> Septiembre { get; set; }
        public Nullable<double> Octubre { get; set; }
        public Nullable<double> Noviembre { get; set; }
        public Nullable<double> Diciembre { get; set; }
        public Nullable<double> Enero_Base { get; set; }
        public Nullable<double> Febrero_Base { get; set; }
        public Nullable<double> Marzo_Base { get; set; }
        public Nullable<double> Abril_Base { get; set; }
        public Nullable<double> Mayo_Base { get; set; }
        public Nullable<double> Junio_Base { get; set; }
        public Nullable<double> Julio_Base { get; set; }
        public Nullable<double> Agosto_Base { get; set; }
        public Nullable<double> Septiembre_Base { get; set; }
        public Nullable<double> Octubre_Base { get; set; }
        public Nullable<double> Noviembre_Base { get; set; }
        public Nullable<double> Diciembre_Base { get; set; }
    }
}
